services:
    example-discord-bot:
        build:
            context: .
        container_name: example-discord-bot
        restart: "no"
        secrets:
          - discord_token
        ports:
          - "8000:8000"

secrets:
    discord_token:
        file: ./secrets/discord_token.txt
