services:
    site:
        build:
            context: .
            dockerfile: Dockerfile.site
        container_name: site
        restart: "no"
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=host.docker.internal
    
    bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        container_name: bot
        restart: "no"
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=host.docker.internal
