services:
    site:
        build:
            context: .
            dockerfile: Dockerfile.site
        container_name: site
        restart: "no"
        env_file: .env
        environment:
            - POSTGRES_HOST=host.docker.internal
    
    bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        container_name: bot
        restart: "no"
        env_file: .env
        environment:
            - POSTGRES_HOST=host.docker.internal
