services:
    ranking:
        build:
            context: .
        container_name: ranking
        restart: "no"
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=host.docker.internal
