# Generated by Django 5.1.5 on 2025-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='message_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('ranking', 'message_id')},
        ),
    ]
