# Generated by Django 5.1.5 on 2025-05-26 11:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_entry_message_id_alter_entry_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active_from', models.DateTimeField(default=datetime.datetime(2025, 5, 26, 13, 59, 51, 393103))),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ranking')),
            ],
        ),
    ]
