# Generated by Django 5.1.5 on 2025-09-28 22:26

import annoying.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models

def move_reverse_sort_to_settings(apps, schema_editor):
    # Get the Ranking model
    Ranking = apps.get_model('website', 'Ranking')

    # Iterate over all Ranking objects and update the settings field
    for ranking in Ranking.objects.all():
        # Update the settings field with the reverse_sort value
        settings = ranking.settings
        settings.reverse_sort = ranking.reverse_sort
        settings.save()

def move_reverse_sort_from_settings(apps, schema_editor):
    # Get the Ranking model
    Ranking = apps.get_model('website', 'Ranking')

    # Iterate over all Ranking objects and update the reverse_sort field
    for ranking in Ranking.objects.all():
        # Update the reverse_sort field from the settings field
        settings = ranking.settings
        ranking.reverse_sort = settings.reverse_sort
        ranking.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_subranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('ranking', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.ranking')),
                ('reverse_sort', models.BooleanField(default=False)),
                ('is_timestamp', models.BooleanField(default=False)),
                ('mean', models.CharField(choices=[(None, 'none'), ('all', 'All'), ('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('entry', 'Entry')], max_length=10)),
                ('median', models.CharField(choices=[(None, 'none'), ('all', 'All'), ('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('entry', 'Entry')], max_length=10)),
            ],
        ),
        migrations.RunPython(move_reverse_sort_to_settings, move_reverse_sort_from_settings),
        migrations.RemoveField(
            model_name='ranking',
            name='reverse_sort',
        ),
        migrations.AlterField(
            model_name='subranking',
            name='active_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 0, 26, 8, 837510)),
        ),
    ]
