# Generated by Django 5.1.5 on 2025-05-12 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('reverse_sort', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.FloatField(default=1)),
                ('user', models.BigIntegerField()),
                ('message_id', models.BigIntegerField(unique=True)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ranking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('string', models.CharField(max_length=200)),
                ('value', models.FloatField(default=1)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ranking')),
            ],
            options={
                'unique_together': {('ranking', 'string')},
            },
        ),
        migrations.CreateModel(
            name='RankingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.BigIntegerField()),
                ('guild_id', models.BigIntegerField()),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ranking')),
            ],
            options={
                'unique_together': {('ranking', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('user', models.BigIntegerField()),
                ('guild_id', models.BigIntegerField()),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ranking')),
            ],
            options={
                'unique_together': {('user', 'ranking', 'guild_id')},
            },
        ),
    ]
