# Generated by Django 5.1.5 on 2025-01-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_ranking_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='character',
            field=models.CharField(default='+', max_length=200),
        ),
    ]
