# Generated by Django 5.1.5 on 2025-01-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_entry_number_alter_ranking_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='message_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
