# Generated by Django 5.1.5 on 2025-01-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_entry_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
