# Generated by Django 5.1.5 on 2025-01-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_entry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='character',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
