# Generated by Django 5.1.5 on 2025-01-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_ranking_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='character',
            new_name='token',
        ),
    ]
