# Generated by Django 5.1.5 on 2025-01-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_character_ranking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
