# Generated by Django 5.1.5 on 2025-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_ranking_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caffeine_content',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('caffeine', models.FloatField(default=0)),
            ],
        ),
    ]
