# Generated by Django 5.1.5 on 2025-01-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_user_alter_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='reverse_sorting',
            field=models.BooleanField(default=False),
        ),
    ]
